
sudo: true

language: cpp
cache:
  apt: true

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'g++-5']
      env:
        - COMPILERCC=gcc-5
        - COMPILERCXX=g++-5

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILERCC=clang-4.0
        - COMPILERCXX=clang++-4.0


    - os: osx
      compiler: gcc
      env:
        - COMPILERCC=gcc
        - COMPILERCXX=g++

    - os: osx
      compiler: clang
      env:
        - COMPILERCC=clang
        - COMPILERCXX=clang++


install:
  - if [ $TRAVIS_OS_NAME = linux ]; then ./housekeeping/install_deps_linux.sh; fi
  - if [ $TRAVIS_OS_NAME = osx   ]; then ./housekeeping/install_deps_osx.sh  ; fi

script:
  - mkdir build
  - cd build
  - export CC=$COMPILERCC; export CXX=$COMPILERCXX
  # build ref10 with sha2
  - cmake .. -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" -DEDIMPL=ref10 -DHASH=sha2_openssl -DRANDOM=rand_openssl
  - make
  - ctest
  # build ref10 with sha3
  - cmake .. -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" -DEDIMPL=ref10 -DHASH=sha3_brainhub -DRANDOM=dev_urandom
  - make
  - ctest
  # build amd64-24-24k-pic
  - cmake .. -DEDIMPL=amd64-64-24k-pic -DHASH=sha3_brainhub -DRANDOM=dev_urandom
  - make
  - ctest
  # build amd64-64-24k
  - cmake .. -DEDIMPL=amd64-64-24k -DHASH=sha3_brainhub -DRANDOM=dev_urandom
  - make
  - ctest
  